
import React, { useState, useEffect } from 'react';
import { Sparkles, RefreshCcw, AlertCircle, TrendingUp, DollarSign } from 'lucide-react';
import { AIInsight } from '../types';
// Fixed: getMarketingInsights does not exist, using getAdvancedInsights instead
import { getAdvancedInsights } from '../services/geminiService';

interface InsightsPanelProps {
  dashboardData: any;
}

const InsightsPanel: React.FC<InsightsPanelProps> = ({ dashboardData }) => {
  const [insights, setInsights] = useState<AIInsight[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchInsights = async () => {
    setLoading(true);
    // Updated to use the correct service function and signature
    const domain = dashboardData?.domain || 'enterprise-analytics.com';
    const data = await getAdvancedInsights(domain, dashboardData);
    setInsights(data);
    setLoading(false);
  };

  useEffect(() => {
    fetchInsights();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'optimization': return <TrendingUp className="w-4 h-4" />;
      case 'budget': return <DollarSign className="w-4 h-4" />;
      case 'anomaly': return <AlertCircle className="w-4 h-4" />;
      default: return <Sparkles className="w-4 h-4" />;
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return 'bg-rose-100 text-rose-700 border-rose-200';
      case 'medium': return 'bg-amber-100 text-amber-700 border-amber-200';
      default: return 'bg-blue-100 text-blue-700 border-blue-200';
    }
  };

  return (
    <div className="bg-slate-900 text-white p-6 rounded-2xl shadow-xl h-full flex flex-col">
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-2">
          <Sparkles className="w-6 h-6 text-indigo-400" />
          <h2 className="text-xl font-bold tracking-tight">Gemini Insights</h2>
        </div>
        <button 
          onClick={fetchInsights}
          disabled={loading}
          className="p-2 hover:bg-slate-800 rounded-lg transition-colors disabled:opacity-50"
        >
          <RefreshCcw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      <div className="space-y-6 flex-1 overflow-y-auto custom-scrollbar pr-2">
        {loading ? (
          <div className="space-y-4">
            {[1, 2, 3].map(i => (
              <div key={i} className="animate-pulse bg-slate-800 h-32 rounded-xl" />
            ))}
          </div>
        ) : (
          insights.map((insight, idx) => (
            <div key={idx} className="group bg-slate-800/50 hover:bg-slate-800 border border-slate-700/50 p-5 rounded-xl transition-all">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-indigo-400">
                  {getCategoryIcon(insight.category)}
                  <span className="text-[10px] uppercase font-bold tracking-widest">{insight.category}</span>
                </div>
                <span className={`text-[10px] px-2 py-0.5 rounded-full border font-bold uppercase ${getPriorityColor(insight.priority)}`}>
                  {insight.priority}
                </span>
              </div>
              <h3 className="font-semibold text-slate-100 mb-2 leading-tight">{insight.title}</h3>
              <p className="text-sm text-slate-400 leading-relaxed">{insight.description}</p>
            </div>
          ))
        )}
      </div>

      <div className="mt-8 pt-6 border-t border-slate-800 text-[11px] text-slate-500 text-center">
        Analysis generated by Gemini 3 Pro • Up to date as of today
      </div>
    </div>
  );
};

export default InsightsPanel;
